// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.github.alexandrenavarro.postprocessorbuilder;

import java.util.Properties;

public class PostProcessorDescriptorBuilder2 extends PostProcessorDescriptorBuilderBase<PostProcessorDescriptorBuilder2> {
    public static PostProcessorDescriptorBuilder2 postProcessorDescriptor() {
        return new PostProcessorDescriptorBuilder2();
    }

    public PostProcessorDescriptorBuilder2() {
        super(new PostProcessorDescriptor());
    }

    public PostProcessorDescriptor build() {
        return getInstance();
    }
}

class PostProcessorDescriptorBuilderBase<GeneratorT extends PostProcessorDescriptorBuilderBase<GeneratorT>> {
    private PostProcessorDescriptor instance;

    protected PostProcessorDescriptorBuilderBase(PostProcessorDescriptor aInstance) {
        instance = aInstance;
    }

    protected PostProcessorDescriptor getInstance() {
        return instance;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withFolder(String aValue) {
        instance.setFolder(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withHandlers(String[] aValue) {
        instance.setHandlers(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withName(String aValue) {
        instance.setName(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withPluginKey(String aValue) {
        instance.setPluginKey(aValue);

        return (GeneratorT) this;
    }

    @SuppressWarnings("unchecked")
    public GeneratorT withProperties(Properties aValue) {
        instance.setProperties(aValue);

        return (GeneratorT) this;
    }
}
